In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import pydotplus

In [4]:
from sklearn.datasets import load_iris

In [5]:
from sklearn import tree

In [6]:
data = pd.read_csv('CO2_Emissions_metric_tons_per_capita_Canada_1960_to_2018.csv')

In [7]:
data

    Year  CO2_Emissions
0   1960      10.770847
1   1961      10.627898
2   1962      11.130627
3   1963      11.132102
4   1964      12.305370
5   1965      12.814001
6   1966      12.934918
7   1967      13.810355
8   1968      14.632645
9   1969      14.618649
10  1970      16.014149
11  1971      16.055332
12  1972      17.154066
13  1973      16.967135
14  1974      17.098006
15  1975      17.160209
16  1976      17.028624
17  1977      17.202835
18  1978      17.355629
19  1979      18.266101
20  1980      18.079621
21  1981      17.324935
22  1982      16.515189
23  1983      16.111326
24  1984      16.620253
25  1985      16.332990
26  1986      15.519113
27  1987      16.310195
28  1988      17.022174
29  1989      16.984193
30  1990      15.135528
31  1991      14.727817
32  1992      15.015193
33  1993      14.735349
34  1994      15.131378
35  1995      15.340087
36  1996      15.641898
37  1997      16.001165
38  1998      16.141841
39  1999      16.286811
40  2000      16.783045
41  2001      16.341885
42  2002      16.756016
43  2003      17.234216
44  2004      16.820256
45  2005      17.056637
46  2006      16.611928
47  2007      17.370840
48  2008      16.548803
49  2009      15.486682
50  2010      15.733914
51  2011      15.950225
52  2012      15.761264
53  2013      15.858129
54  2014      15.854138
55  2015      15.651386
56  2016      15.244747
57  2017      15.385291
58  2018      15.497025

In [8]:
x = data.iloc[:,[0,1]] 
x 
from sklearn.preprocessing import LabelEncoder  
labelencoder_x = LabelEncoder() 
x = x.apply(LabelEncoder().fit_transform) 
x

    Year  CO2_Emissions
0      0              1
1      1              0
2      2              2
3      3              3
4      4              4
5      5              5
6      6              6
7      7              7
8      8              9
9      9              8
10    10             29
11    11             30
12    12             50
13    13             44
14    14             49
15    15             51
16    16             47
17    17             52
18    18             55
19    19             58
20    20             57
21    21             54
22    22             37
23    23             31
24    24             40
25    25             35
26    26             20
27    27             34
28    28             46
29    29             45
30    30             14
31    31             10
32    32             12
33    33             11
34    34             13
35    35             16
36    36             21
37    37             28
38    38             32
39    39             33
40    40             42
41    41             36
42    42             41
43    43             53
44    44             43
45    45             48
46    46             39
47    47             56
48    48             38
49    49             18
50    50             23
51    51             27
52    52             24
53    53             26
54    54             25
55    55             22
56    56             15
57    57             17
58    58             19

In [9]:
from sklearn.tree import DecisionTreeClassifier  
regressor = DecisionTreeClassifier()

In [10]:
y = data.iloc[:,0] 
y

0     1960
1     1961
2     1962
3     1963
4     1964
5     1965
6     1966
7     1967
8     1968
9     1969
10    1970
11    1971
12    1972
13    1973
14    1974
15    1975
16    1976
17    1977
18    1978
19    1979
20    1980
21    1981
22    1982
23    1983
24    1984
25    1985
26    1986
27    1987
28    1988
29    1989
30    1990
31    1991
32    1992
33    1993
34    1994
35    1995
36    1996
37    1997
38    1998
39    1999
40    2000
41    2001
42    2002
43    2003
44    2004
45    2005
46    2006
47    2007
48    2008
49    2009
50    2010
51    2011
52    2012
53    2013
54    2014
55    2015
56    2016
57    2017
58    2018
Name: Year, dtype: int64

In [4]:
regressor.fit(x.iloc[:,0:2],y) 
x_in = np.array([0,1]) 
y_prediction = regressor.predict([x_in])  
y_prediction

NameError: name 'regressor' is not defined

In [12]:
model = DecisionTreeClassifier() 
model.fit(x,y)

DecisionTreeClassifier()

In [13]:
pip install six

Requirement already satisfied: six in c:\users\lenovo\anaconda3\lib\site-packages (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [14]:
import six 
import sys 
sys.modules['sklearn.externals.six'] = six  
from io import StringIO 
import io

In [15]:
from IPython.display import Image

In [16]:
conda install pydotplus

Note: you may need to restart the kernel to use updated packages.Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done


# All requested packages already installed.

Retrieving notices: ...working... done

In [17]:
pip install graphviz

Requirement already satisfied: graphviz in c:\users\lenovo\anaconda3\lib\site-packages (0.20.1)
Note: you may need to restart the kernel to use updated packages.

In [18]:
conda install python-graphviz

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

Retrieving notices: ...working... done

Note: you may need to restart the kernel to use updated packages.

In [19]:
from sklearn. tree import export_graphviz

In [20]:
dot_data = StringIO()

In [21]:
tree.export_graphviz(regressor, out_file = dot_data, filled = True, rounded = True, special_characters = True) 
graph = pydotplus.graph_from_dot_data(dot_data.getvalue()) 
(graph.write_png('treeViewer.png'))

True